### ISSUE TITLE
[PE-D] No way to see everyone in a folder

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T16-1/tp#149]
Folder 1 is supposed to contain 11 people, but not all the friends are listed under the folder1.

![Screenshot 2021-10-29 at 4.46.36 PM.png](https://raw.githubusercontent.com/tau-bar/ped/main/files/a02bb4f2-85e2-4ea0-9503-aa94bf1c2ab2.png)

As far as I can see from the user guide, there is no way to see all the friends in that folder?'

![Screenshot 2021-10-29 at 4.48.56 PM.png](https://raw.githubusercontent.com/tau-bar/ped/main/files/563085df-1eec-4c2d-a281-b857b11678b0.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: tau-bar/ped#7

**Comment by sebbycake** [comment]
11 contacts are displayed in the folder though.
