### ISSUE TITLE
[PE-D] Grammatical error in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T16-1/tp#158]
![image.png](https://raw.githubusercontent.com/Lemonsr/ped/main/files/9c5a2ecb-0d49-41d2-be09-b332136fa466.png)

in -> on

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Lemonsr/ped#19

**Comment by sebbycake** [comment]
Also change the AddressBook
