### ISSUE TITLE
[PE-D] Many Error messages missing examples

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T16-1/tp#172]
Many error messages are missing examples making it hard for the user to correct the errors

E.g.

![Screenshot 2021-10-29 at 5.34.45 PM.png](https://raw.githubusercontent.com/ruthpohrp/ped/main/files/e862fd88-92ed-419f-b44f-1a0bac9c653a.png)

Should have its message usage and command format there for user friendliness.
i.e. <br>
`echo: Adds a person to folder in UNIon. Parameters: INDEX >> FOLDERNAME` <br>
`Example: echo 3 >> CS2103`

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ruthpohrp/ped#20

**Comment by sebbycake** [comment]
KIV - We will make a new user story to re-structure our error messages.
